# Generated by Django 6.0.1 on 2026-02-03 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="imagen_url",
        ),
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cliente", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=50)),
                ("direccion", models.TextField()),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("notas", models.TextField(blank=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.producto",
                    ),
                ),
            ],
        ),
    ]
