# Generated by Django 6.0.1 on 2026-02-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_remove_producto_imagen_url_producto_imagen_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="categorias/"),
        ),
    ]
